### ISSUE TITLE
Widget Constants should be ONE complex object

### ISSUE THREAD

**Issue by dnk0** [dnk0/CitationPatterns#37]
![bildschirmfoto 2017-11-08 um 16 09 20](https://user-images.githubusercontent.com/11459505/32556241-31e4197e-c49f-11e7-9b20-1b1e3955b2be.png)

Refactor this to be working with a layout like so:
`{
    RESULTS: {
        name: 'RESULTS',
        description: 'Results for: '
    },
    ...
}`

**Comment by dnk0** [comment]
think about how to refactor 

if type === WidgetTypeNames.RESULTS
without the ugly version 
if type === WidgetTypeNames.RESULTS.name

**Comment by SiC42** [comment]
DONE with changes to name-guideline.
Should be discussed in next scrum. Easily changeable.

**Comment by SiC42** [comment]
As of now: WidgetType.results.name
