### ISSUE TITLE
Refactor using semicolon consistently

### ISSUE THREAD

**Issue by SiC42** [dnk0/CitationPatterns#40]
As of now there are places in code where it is used (despite not necessary) and places where it isn't used.

**Comment by dnk0** [comment]
Due tomorrow 
:(

**Comment by SiC42** [comment]
Should be easily done if it gets highlighted by your IDE :)

**Comment by SiC42** [comment]
![semicolon](https://user-images.githubusercontent.com/7562025/32723531-1936b0f8-c86e-11e7-97ad-46458513e20c.png)
