### ISSUE TITLE
NLP Recherche

### ISSUE THREAD

**Issue by dnk0** [dnk0/CitationPatterns#48]
A short summary should be made to every point in this discussion
We will extract the information we will need in the next scrum meeting to a document referenced in the readme summary.
* [] https://github.com/diasks2/ruby-nlp

**Comment by SiC42** [comment]
We should probably also talk with our advisor about this. 
Unfortunatly it is not a simple thing to extract why a paper was referenced

**Comment by dnk0** [comment]
lets see what we can find until friday
if we can't find anything useful we should probably ask dr. efer about this , yes

**Comment by dnk0** [comment]
Put all the stuff in here
https://github.com/dnk0/CitationPatterns/wiki/NLP-Research

**Comment by dnk0** [comment]
We should be able to answer some of the following questions:

- What papers belong to the same discussion ? 
- What paper cover similar topics ?
- What papers are relevant for a specific research interest ?
- Has a cite/reference a specific motivion? Is it critique, supporting, etc. ?

If you want to add more questions pls copy all of them together with the old ones in a new comment.

**Comment by dnk0** [comment]
more papers in wiki

**Comment by dnk0** [comment]
i'll try to write some summaries over the wknd
