### ISSUE TITLE
Backend route for statistics

### ISSUE THREAD

**Issue by dnk0** [dnk0/CitationPatterns#51]
Create a backend route which should give statistics about the dataset such as:

* [ ] diameter
* [x] count of papers
* [x] count of authors
* [x] count of nodes
* [x] count of :wrote references
* [x] count of :references references
* [x] count of relationships
* [x] average degree of papers
* [x] average degree of authors
* [x] average degree of nodes
* [ ] node count of the largest connected component

Consider adding other interesting properties

Also consider displaying them in the tooltips already
If not please open another ticket issuing this. 
rel: #50

**Comment by dnk0** [comment]
That's what i will use for now for the computation of the diameter: 

START n=node(*)
MATCH p=(n)-[:references|wrote*]->(m) 
WITH COLLECT(p) AS paths, MAX(length(p)) AS maxLength 
RETURN FILTER(path IN paths 
  WHERE length(path)= maxLength) AS longestPaths

**Comment by SiC42** [comment]
Just calc it once a month or something

**Comment by dnk0** [comment]
Ye but query computation doesn't fit on the heap.
And it's not recomended to increase the heap size

**Comment by dnk0** [comment]
example output for the ANN dataset

![bildschirmfoto 2017-11-15 um 14 36 20](https://user-images.githubusercontent.com/11459505/32838848-9f0cd4dc-ca12-11e7-9049-5ef77e05ae0b.png)
