### ISSUE TITLE
Implement Term Frequency in/as Widget

### ISSUE THREAD

**Issue by SiC42** [dnk0/CitationPatterns#73]
See [Tf-idf](https://en.wikipedia.org/wiki/Tf–idf)

**Comment by dnk0** [comment]
u sure u filtered stopwords?
![bildschirmfoto 2017-11-27 um 17 22 22](https://user-images.githubusercontent.com/11459505/33277019-95f3087e-d397-11e7-88c7-c17a11187c72.png)

**Comment by SiC42** [comment]
Let's talk tomorrow
