### ISSUE TITLE
Fix "method_lines" issue in src/f_spacial/config/webpackDevServer.config.js

### ISSUE THREAD

**Issue by dnk0** [dnk0/CitationPatterns#8]
Function `exports` has 26 lines of code (exceeds 25 allowed). Consider refactoring.

https://codeclimate.com/github/dnk0/CitationPatterns/src/f_spacial/config/webpackDevServer.config.js#issue_59f79e742e589300010000b1

**Comment by SiC42** [comment]
don't fix script files
