### ISSUE TITLE
Performanceenhancing for autocomplete calculation

### ISSUE THREAD

**Issue by dnk0** [dnk0/CitationPatterns#87]
right now i autocomplete using a state like: 

```ruby
queryString = params[:query].scan(/./).join('.*')
queryString.prepend('.*')
queryString << '.*'   
@papers = Paper.where(:title => /#{queryString}/).limit(10)
@authors = Author.query_as(:a).where("(a.first_name + ' ' + a.last_name) =~ \"(?i)#{queryString}\"").pluck(:a)
```

rel: [Stackoverflow - Find rows where integer sequence contains a given subsequence](https://dba.stackexchange.com/questions/108373/find-rows-where-integer-sequence-contains-a-given-subsequence/108402#108402)

This seems expensive af to do for every keypress event.
Consider enhancing this.

**Comment by SiC42** [comment]
Probably better to use software made for this, i.e. ElasticSearch/Solr. Ofc it would cost memory for indexing
