### ISSUE TITLE
Multiple Databases

### ISSUE THREAD

**Issue by dnk0** [dnk0/CitationPatterns#90]
Config the spring framework to be able to use multiple databases.
fulltexts should be persisted in the mongodb database while the metadata should be persisted in the neo4j graph.
rel:
http://www.baeldung.com/spring-data-jpa-multiple-databases
rel:
https://medium.com/@joeclever/using-multiple-datasources-with-spring-boot-and-spring-data-6430b00c02e7
rel:
https://stackoverflow.com/questions/41226267/using-spring-data-mongodb-and-spring-data-neo4j-together

**Comment by SiC42** [comment]
rel:
https://github.com/spring-projects/spring-data-multistore-test

**Comment by SiC42** [comment]
Using the current implementation returns 
>{
cause: null,
message: "Id must be assignable to Serializable!: null"
}

When using the /contents path

**Comment by dnk0** [comment]
![giphy](https://user-images.githubusercontent.com/11459505/38165690-a0be1e56-3517-11e8-9574-6bf1e28b1dea.gif)
